/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/HxjeXU3Qv7g
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Input } from "@/components/ui/input"

export function tools() {
  return (
    <div className="flex h-screen">
      <aside className="w-1/4 border-r p-4 flex flex-col justify-between">
        <div className="space-y-4">
          <div className="font-bold">Creative Cook AI</div>
          <div className="text-muted-foreground">Chats</div>
        </div>
        <div className="flex items-center space-x-2">
          <Avatar>
            <AvatarImage src="/placeholder-user.jpg" alt="User" />
            <AvatarFallback>U</AvatarFallback>
          </Avatar>
          <span>User</span>
        </div>
      </aside>
      <main className="flex-1 flex flex-col items-center justify-center">
        <h1 className="text-6xl font-bold">Creative Cook AI</h1>
        <div className="mt-8 w-1/2">
          <Input placeholder="Type here..." className="w-full" />
        </div>
      </main>
    </div>
  )
}
