/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/5hB3RQwnV3V
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { IBM_Plex_Sans } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

ibm_plex_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Card, CardContent } from "@/components/ui/card"

export function op() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <header className="px-4 lg:px-6 h-14 flex items-center">
        <Link href="#" className="flex items-center justify-center" prefetch={false}>
          <CookingPotIcon className="h-6 w-6" />
          <span className="sr-only">Generative Cooking</span>
        </Link>
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            Recipes
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            About
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            Contact
          </Link>
        </nav>
      </header>
      <main className="flex-1">
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <div className="grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px]">
              <div className="flex flex-col justify-center space-y-4">
                <div className="space-y-2">
                  <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none">
                    Discover Delicious Recipes
                  </h1>
                  <p className="max-w-[600px] text-muted-foreground md:text-xl">
                    Explore a world of culinary possibilities with our generative cooking platform. Unleash your
                    creativity and discover new flavors.
                  </p>
                </div>
                <div className="flex flex-col gap-2 min-[400px]:flex-row">
                  <Link
                    href="#"
                    className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                    prefetch={false}
                  >
                    Explore Recipes
                  </Link>
                </div>
              </div>
              <img
                src="/placeholder.svg"
                width="550"
                height="550"
                alt="Hero"
                className="mx-auto aspect-video overflow-hidden rounded-xl object-cover sm:w-full lg:order-last lg:aspect-square"
              />
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-muted">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Featured Recipes</h2>
                <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Explore a curated selection of our most popular and delicious recipes.
                </p>
              </div>
            </div>
            <div className="mx-auto grid max-w-5xl items-start gap-6 py-12 sm:grid-cols-2 md:grid-cols-3 lg:gap-12">
              <Card className="h-full w-full">
                <img
                  src="/placeholder.svg"
                  width="550"
                  height="310"
                  alt="Recipe"
                  className="mx-auto aspect-video overflow-hidden rounded-t-xl object-cover object-center sm:w-full"
                />
                <CardContent className="space-y-2">
                  <h3 className="text-lg font-bold">Creamy Mushroom Risotto</h3>
                  <p className="text-muted-foreground">
                    A rich and flavorful risotto made with fresh mushrooms and creamy parmesan.
                  </p>
                </CardContent>
              </Card>
              <Card className="h-full w-full">
                <img
                  src="/placeholder.svg"
                  width="550"
                  height="310"
                  alt="Recipe"
                  className="mx-auto aspect-video overflow-hidden rounded-t-xl object-cover object-center sm:w-full"
                />
                <CardContent className="space-y-2">
                  <h3 className="text-lg font-bold">Grilled Salmon with Lemon</h3>
                  <p className="text-muted-foreground">
                    Perfectly grilled salmon fillets with a bright lemon marinade.
                  </p>
                </CardContent>
              </Card>
              <Card className="h-full w-full">
                <img
                  src="/placeholder.svg"
                  width="550"
                  height="310"
                  alt="Recipe"
                  className="mx-auto aspect-video overflow-hidden rounded-t-xl object-cover object-center sm:w-full"
                />
                <CardContent className="space-y-2">
                  <h3 className="text-lg font-bold">Vegetable Stir-Fry</h3>
                  <p className="text-muted-foreground">
                    A colorful and healthy stir-fry with fresh vegetables and a flavorful sauce.
                  </p>
                </CardContent>
              </Card>
              <Card className="h-full w-full">
                <img
                  src="/placeholder.svg"
                  width="550"
                  height="310"
                  alt="Recipe"
                  className="mx-auto aspect-video overflow-hidden rounded-t-xl object-cover object-center sm:w-full"
                />
                <CardContent className="space-y-2">
                  <h3 className="text-lg font-bold">Beef Stroganoff</h3>
                  <p className="text-muted-foreground">
                    A classic comfort food dish with tender beef, mushrooms, and a creamy sauce.
                  </p>
                </CardContent>
              </Card>
              <Card className="h-full w-full">
                <img
                  src="/placeholder.svg"
                  width="550"
                  height="310"
                  alt="Recipe"
                  className="mx-auto aspect-video overflow-hidden rounded-t-xl object-cover object-center sm:w-full"
                />
                <CardContent className="space-y-2">
                  <h3 className="text-lg font-bold">Roasted Vegetable Medley</h3>
                  <p className="text-muted-foreground">
                    A delicious mix of roasted vegetables, seasoned to perfection.
                  </p>
                </CardContent>
              </Card>
              <Card className="h-full w-full">
                <img
                  src="/placeholder.svg"
                  width="550"
                  height="310"
                  alt="Recipe"
                  className="mx-auto aspect-video overflow-hidden rounded-t-xl object-cover object-center sm:w-full"
                />
                <CardContent className="space-y-2">
                  <h3 className="text-lg font-bold">Lemon Garlic Shrimp</h3>
                  <p className="text-muted-foreground">Succulent shrimp sautéed in a zesty lemon and garlic sauce.</p>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
      </main>
      <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
        <p className="text-xs text-muted-foreground">&copy; 2024 Generative Cooking. All rights reserved.</p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link href="#" className="text-xs hover:underline underline-offset-4" prefetch={false}>
            Terms of Service
          </Link>
          <Link href="#" className="text-xs hover:underline underline-offset-4" prefetch={false}>
            Privacy
          </Link>
        </nav>
      </footer>
    </div>
  )
}

function CookingPotIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M2 12h20" />
      <path d="M20 12v8a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2v-8" />
      <path d="m4 8 16-4" />
      <path d="m8.86 6.78-.45-1.81a2 2 0 0 1 1.45-2.43l1.94-.48a2 2 0 0 1 2.43 1.46l.45 1.8" />
    </svg>
  )
}
